# Generated by Django 4.2.1 on 2023-05-10 09:23

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import job.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                ("description", models.TextField(null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("address", models.CharField(max_length=2000, null=True)),
                (
                    "jobType",
                    models.CharField(
                        choices=[
                            ("Permanent", "Permanent"),
                            ("Temporary", "Temporary"),
                            ("Intership", "Intership"),
                        ],
                        default="Permanent",
                        max_length=200,
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("Bachelors", "Bachelors"),
                            ("Masters", "Masters"),
                            ("Phd", "Phd"),
                        ],
                        default="Bachelors",
                        max_length=200,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("Business", "Business"),
                            ("Tech", "Tech"),
                            ("Transportation", "Transportation"),
                        ],
                        default="Business",
                        max_length=200,
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("NoEXPERIENCE", "No Experience"),
                            ("1 Years", "One Year"),
                            ("2 Years", "Two Year"),
                            ("3 Years Above", "Three Plus"),
                        ],
                        default="NoEXPERIENCE",
                        max_length=200,
                    ),
                ),
                ("salary", models.IntegerField(default=1)),
                ("position", models.IntegerField(default=-1)),
                ("company", models.CharField(max_length=2000, null=True)),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326
                    ),
                ),
                ("lastDate", models.DateTimeField(default=job.models.return_date_time)),
                ("create_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
